// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listener.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Api.V2.Listener2 {

  /// <summary>Holder for reflection information generated from listener.proto</summary>
  public static partial class ListenerReflection {

    #region Descriptor
    /// <summary>File descriptor for listener.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ListenerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5saXN0ZW5lci5wcm90bxIWZW52b3kuYXBpLnYyLmxpc3RlbmVyMhofZW52",
            "b3kvYXBpL3YyL2NvcmUvYWRkcmVzcy5wcm90bxocZW52b3kvYXBpL3YyL2F1",
            "dGgvY2VydC5wcm90bxocZW52b3kvYXBpL3YyL2NvcmUvYmFzZS5wcm90bxoc",
            "Z29vZ2xlL3Byb3RvYnVmL3N0cnVjdC5wcm90bxoeZ29vZ2xlL3Byb3RvYnVm",
            "L3dyYXBwZXJzLnByb3RvGhd2YWxpZGF0ZS92YWxpZGF0ZS5wcm90bxoUZ29n",
            "b3Byb3RvL2dvZ28ucHJvdG8isAEKBkZpbHRlchIXCgRuYW1lGAEgASgJQgm6",
            "6cADBHICIAESJwoGY29uZmlnGAIgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0",
            "cnVjdBJGCg1kZXByZWNhdGVkX3YxGAMgASgLMisuZW52b3kuYXBpLnYyLmxp",
            "c3RlbmVyMi5GaWx0ZXIuRGVwcmVjYXRlZFYxQgIYARocCgxEZXByZWNhdGVk",
            "VjESDAoEdHlwZRgBIAEoCSLOAgoQRmlsdGVyQ2hhaW5NYXRjaBITCgtzbmlf",
            "ZG9tYWlucxgBIAMoCRIzCg1wcmVmaXhfcmFuZ2VzGAMgAygLMhwuZW52b3ku",
            "YXBpLnYyLmNvcmUuQ2lkclJhbmdlEhYKDmFkZHJlc3Nfc3VmZml4GAQgASgJ",
            "EjAKCnN1ZmZpeF9sZW4YBSABKAsyHC5nb29nbGUucHJvdG9idWYuVUludDMy",
            "VmFsdWUSOgoUc291cmNlX3ByZWZpeF9yYW5nZXMYBiADKAsyHC5lbnZveS5h",
            "cGkudjIuY29yZS5DaWRyUmFuZ2USMgoMc291cmNlX3BvcnRzGAcgAygLMhwu",
            "Z29vZ2xlLnByb3RvYnVmLlVJbnQzMlZhbHVlEjYKEGRlc3RpbmF0aW9uX3Bv",
            "cnQYCCABKAsyHC5nb29nbGUucHJvdG9idWYuVUludDMyVmFsdWUi6gIKC0Zp",
            "bHRlckNoYWluEkQKEmZpbHRlcl9jaGFpbl9tYXRjaBgBIAEoCzIoLmVudm95",
            "LmFwaS52Mi5saXN0ZW5lcjIuRmlsdGVyQ2hhaW5NYXRjaBI8Cgt0bHNfY29u",
            "dGV4dBgCIAEoCzInLmVudm95LmFwaS52Mi5hdXRoLkRvd25zdHJlYW1UbHND",
            "b250ZXh0EjUKB2ZpbHRlcnMYAyADKAsyHi5lbnZveS5hcGkudjIubGlzdGVu",
            "ZXIyLkZpbHRlckIEyN4fABIzCg91c2VfcHJveHlfcHJvdG8YBCABKAsyGi5n",
            "b29nbGUucHJvdG9idWYuQm9vbFZhbHVlEi0KCG1ldGFkYXRhGAUgASgLMhsu",
            "ZW52b3kuYXBpLnYyLmNvcmUuTWV0YWRhdGESPAoQdHJhbnNwb3J0X3NvY2tl",
            "dBgGIAEoCzIiLmVudm95LmFwaS52Mi5jb3JlLlRyYW5zcG9ydFNvY2tldCJS",
            "Cg5MaXN0ZW5lckZpbHRlchIXCgRuYW1lGAEgASgJQgm66cADBHICIAESJwoG",
            "Y29uZmlnGAIgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdEIOWghsaXN0",
            "ZW5lcqjiHgFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Envoy.Api.V2.Core.AddressReflection.Descriptor, global::Envoy.Api.V2.Auth.CertReflection.Descriptor, global::Envoy.Api.V2.Core.BaseReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, global::Gogoproto.GogoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Listener2.Filter), global::Envoy.Api.V2.Listener2.Filter.Parser, new[]{ "Name", "Config", "DeprecatedV1" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Listener2.Filter.Types.DeprecatedV1), global::Envoy.Api.V2.Listener2.Filter.Types.DeprecatedV1.Parser, new[]{ "Type" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Listener2.FilterChainMatch), global::Envoy.Api.V2.Listener2.FilterChainMatch.Parser, new[]{ "SniDomains", "PrefixRanges", "AddressSuffix", "SuffixLen", "SourcePrefixRanges", "SourcePorts", "DestinationPort" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Listener2.FilterChain), global::Envoy.Api.V2.Listener2.FilterChain.Parser, new[]{ "FilterChainMatch", "TlsContext", "Filters", "UseProxyProto", "Metadata", "TransportSocket" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Api.V2.Listener2.ListenerFilter), global::Envoy.Api.V2.Listener2.ListenerFilter.Parser, new[]{ "Name", "Config" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Filter : pb::IMessage<Filter> {
    private static readonly pb::MessageParser<Filter> _parser = new pb::MessageParser<Filter>(() => new Filter());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Filter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Api.V2.Listener2.ListenerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Filter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Filter(Filter other) : this() {
      name_ = other.name_;
      Config = other.config_ != null ? other.Config.Clone() : null;
      DeprecatedV1 = other.deprecatedV1_ != null ? other.DeprecatedV1.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Filter Clone() {
      return new Filter(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The name of the filter to instantiate. The name must match a supported
    /// filter. The built-in filters are:
    ///
    /// [#comment:TODO(mattklein123): Auto generate the following list]
    /// * :ref:`envoy.client_ssl_auth&lt;config_network_filters_client_ssl_auth>`
    /// * :ref:`envoy.echo &lt;config_network_filters_echo>`
    /// * :ref:`envoy.http_connection_manager &lt;config_http_conn_man>`
    /// * :ref:`envoy.mongo_proxy &lt;config_network_filters_mongo_proxy>`
    /// * :ref:`envoy.ratelimit &lt;config_network_filters_rate_limit>`
    /// * :ref:`envoy.redis_proxy &lt;config_network_filters_redis_proxy>`
    /// * :ref:`envoy.tcp_proxy &lt;config_network_filters_tcp_proxy>`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Struct config_;
    /// <summary>
    /// Filter specific configuration which depends on the filter being
    /// instantiated. See the supported filters for further documentation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Struct Config {
      get { return config_; }
      set {
        config_ = value;
      }
    }

    /// <summary>Field number for the "deprecated_v1" field.</summary>
    public const int DeprecatedV1FieldNumber = 3;
    private global::Envoy.Api.V2.Listener2.Filter.Types.DeprecatedV1 deprecatedV1_;
    /// <summary>
    /// [#not-implemented-hide:]
    /// </summary>
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Listener2.Filter.Types.DeprecatedV1 DeprecatedV1 {
      get { return deprecatedV1_; }
      set {
        deprecatedV1_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Filter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Filter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Config, other.Config)) return false;
      if (!object.Equals(DeprecatedV1, other.DeprecatedV1)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (config_ != null) hash ^= Config.GetHashCode();
      if (deprecatedV1_ != null) hash ^= DeprecatedV1.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (config_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Config);
      }
      if (deprecatedV1_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DeprecatedV1);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (config_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
      }
      if (deprecatedV1_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeprecatedV1);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Filter other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.config_ != null) {
        if (config_ == null) {
          config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        Config.MergeFrom(other.Config);
      }
      if (other.deprecatedV1_ != null) {
        if (deprecatedV1_ == null) {
          deprecatedV1_ = new global::Envoy.Api.V2.Listener2.Filter.Types.DeprecatedV1();
        }
        DeprecatedV1.MergeFrom(other.DeprecatedV1);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (config_ == null) {
              config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(config_);
            break;
          }
          case 26: {
            if (deprecatedV1_ == null) {
              deprecatedV1_ = new global::Envoy.Api.V2.Listener2.Filter.Types.DeprecatedV1();
            }
            input.ReadMessage(deprecatedV1_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Filter message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// [#not-implemented-hide:]
      /// </summary>
      public sealed partial class DeprecatedV1 : pb::IMessage<DeprecatedV1> {
        private static readonly pb::MessageParser<DeprecatedV1> _parser = new pb::MessageParser<DeprecatedV1>(() => new DeprecatedV1());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<DeprecatedV1> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Envoy.Api.V2.Listener2.Filter.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public DeprecatedV1() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public DeprecatedV1(DeprecatedV1 other) : this() {
          type_ = other.type_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public DeprecatedV1 Clone() {
          return new DeprecatedV1(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private string type_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Type {
          get { return type_; }
          set {
            type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as DeprecatedV1);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(DeprecatedV1 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Type != other.Type) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Type.Length != 0) hash ^= Type.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Type.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Type);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Type.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(DeprecatedV1 other) {
          if (other == null) {
            return;
          }
          if (other.Type.Length != 0) {
            Type = other.Type;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Type = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  /// <summary>
  /// Specifies the match criteria for selecting a specific filter chain for a
  /// listener.
  /// </summary>
  public sealed partial class FilterChainMatch : pb::IMessage<FilterChainMatch> {
    private static readonly pb::MessageParser<FilterChainMatch> _parser = new pb::MessageParser<FilterChainMatch>(() => new FilterChainMatch());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FilterChainMatch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Api.V2.Listener2.ListenerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilterChainMatch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilterChainMatch(FilterChainMatch other) : this() {
      sniDomains_ = other.sniDomains_.Clone();
      prefixRanges_ = other.prefixRanges_.Clone();
      addressSuffix_ = other.addressSuffix_;
      SuffixLen = other.SuffixLen;
      sourcePrefixRanges_ = other.sourcePrefixRanges_.Clone();
      sourcePorts_ = other.sourcePorts_.Clone();
      DestinationPort = other.DestinationPort;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilterChainMatch Clone() {
      return new FilterChainMatch(this);
    }

    /// <summary>Field number for the "sni_domains" field.</summary>
    public const int SniDomainsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_sniDomains_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> sniDomains_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// If non-empty, the SNI domains to consider. May contain a wildcard prefix,
    /// e.g. ``*.example.com``.
    ///
    /// .. attention::
    ///
    ///   See the :ref:`FAQ entry &lt;faq_how_to_setup_sni>` on how to configure SNI for more
    ///   information.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> SniDomains {
      get { return sniDomains_; }
    }

    /// <summary>Field number for the "prefix_ranges" field.</summary>
    public const int PrefixRangesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Envoy.Api.V2.Core.CidrRange> _repeated_prefixRanges_codec
        = pb::FieldCodec.ForMessage(26, global::Envoy.Api.V2.Core.CidrRange.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Api.V2.Core.CidrRange> prefixRanges_ = new pbc::RepeatedField<global::Envoy.Api.V2.Core.CidrRange>();
    /// <summary>
    /// If non-empty, an IP address and prefix length to match addresses when the
    /// listener is bound to 0.0.0.0/:: or when use_original_dst is specified.
    /// [#not-implemented-hide:]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Api.V2.Core.CidrRange> PrefixRanges {
      get { return prefixRanges_; }
    }

    /// <summary>Field number for the "address_suffix" field.</summary>
    public const int AddressSuffixFieldNumber = 4;
    private string addressSuffix_ = "";
    /// <summary>
    /// If non-empty, an IP address and suffix length to match addresses when the
    /// listener is bound to 0.0.0.0/:: or when use_original_dst is specified.
    /// [#not-implemented-hide:]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AddressSuffix {
      get { return addressSuffix_; }
      set {
        addressSuffix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "suffix_len" field.</summary>
    public const int SuffixLenFieldNumber = 5;
    private static readonly pb::FieldCodec<uint?> _single_suffixLen_codec = pb::FieldCodec.ForStructWrapper<uint>(42);
    private uint? suffixLen_;
    /// <summary>
    /// [#not-implemented-hide:]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint? SuffixLen {
      get { return suffixLen_; }
      set {
        suffixLen_ = value;
      }
    }

    /// <summary>Field number for the "source_prefix_ranges" field.</summary>
    public const int SourcePrefixRangesFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Envoy.Api.V2.Core.CidrRange> _repeated_sourcePrefixRanges_codec
        = pb::FieldCodec.ForMessage(50, global::Envoy.Api.V2.Core.CidrRange.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Api.V2.Core.CidrRange> sourcePrefixRanges_ = new pbc::RepeatedField<global::Envoy.Api.V2.Core.CidrRange>();
    /// <summary>
    /// The criteria is satisfied if the source IP address of the downstream
    /// connection is contained in at least one of the specified subnets. If the
    /// parameter is not specified or the list is empty, the source IP address is
    /// ignored.
    /// [#not-implemented-hide:]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Api.V2.Core.CidrRange> SourcePrefixRanges {
      get { return sourcePrefixRanges_; }
    }

    /// <summary>Field number for the "source_ports" field.</summary>
    public const int SourcePortsFieldNumber = 7;
    private static readonly pb::FieldCodec<uint?> _repeated_sourcePorts_codec
        = pb::FieldCodec.ForStructWrapper<uint>(58);
    private readonly pbc::RepeatedField<uint?> sourcePorts_ = new pbc::RepeatedField<uint?>();
    /// <summary>
    /// The criteria is satisfied if the source port of the downstream connection
    /// is contained in at least one of the specified ports. If the parameter is
    /// not specified, the source port is ignored.
    /// [#not-implemented-hide:]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint?> SourcePorts {
      get { return sourcePorts_; }
    }

    /// <summary>Field number for the "destination_port" field.</summary>
    public const int DestinationPortFieldNumber = 8;
    private static readonly pb::FieldCodec<uint?> _single_destinationPort_codec = pb::FieldCodec.ForStructWrapper<uint>(66);
    private uint? destinationPort_;
    /// <summary>
    /// Optional destination port to consider when use_original_dst is set on the
    /// listener in determining a filter chain match.
    /// [#not-implemented-hide:]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint? DestinationPort {
      get { return destinationPort_; }
      set {
        destinationPort_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FilterChainMatch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FilterChainMatch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!sniDomains_.Equals(other.sniDomains_)) return false;
      if(!prefixRanges_.Equals(other.prefixRanges_)) return false;
      if (AddressSuffix != other.AddressSuffix) return false;
      if (SuffixLen != other.SuffixLen) return false;
      if(!sourcePrefixRanges_.Equals(other.sourcePrefixRanges_)) return false;
      if(!sourcePorts_.Equals(other.sourcePorts_)) return false;
      if (DestinationPort != other.DestinationPort) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= sniDomains_.GetHashCode();
      hash ^= prefixRanges_.GetHashCode();
      if (AddressSuffix.Length != 0) hash ^= AddressSuffix.GetHashCode();
      if (suffixLen_ != null) hash ^= SuffixLen.GetHashCode();
      hash ^= sourcePrefixRanges_.GetHashCode();
      hash ^= sourcePorts_.GetHashCode();
      if (destinationPort_ != null) hash ^= DestinationPort.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      sniDomains_.WriteTo(output, _repeated_sniDomains_codec);
      prefixRanges_.WriteTo(output, _repeated_prefixRanges_codec);
      if (AddressSuffix.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AddressSuffix);
      }
      if (suffixLen_ != null) {
        _single_suffixLen_codec.WriteTagAndValue(output, SuffixLen);
      }
      sourcePrefixRanges_.WriteTo(output, _repeated_sourcePrefixRanges_codec);
      sourcePorts_.WriteTo(output, _repeated_sourcePorts_codec);
      if (destinationPort_ != null) {
        _single_destinationPort_codec.WriteTagAndValue(output, DestinationPort);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += sniDomains_.CalculateSize(_repeated_sniDomains_codec);
      size += prefixRanges_.CalculateSize(_repeated_prefixRanges_codec);
      if (AddressSuffix.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AddressSuffix);
      }
      if (suffixLen_ != null) {
        size += _single_suffixLen_codec.CalculateSizeWithTag(SuffixLen);
      }
      size += sourcePrefixRanges_.CalculateSize(_repeated_sourcePrefixRanges_codec);
      size += sourcePorts_.CalculateSize(_repeated_sourcePorts_codec);
      if (destinationPort_ != null) {
        size += _single_destinationPort_codec.CalculateSizeWithTag(DestinationPort);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FilterChainMatch other) {
      if (other == null) {
        return;
      }
      sniDomains_.Add(other.sniDomains_);
      prefixRanges_.Add(other.prefixRanges_);
      if (other.AddressSuffix.Length != 0) {
        AddressSuffix = other.AddressSuffix;
      }
      if (other.suffixLen_ != null) {
        if (suffixLen_ == null || other.SuffixLen != 0) {
          SuffixLen = other.SuffixLen;
        }
      }
      sourcePrefixRanges_.Add(other.sourcePrefixRanges_);
      sourcePorts_.Add(other.sourcePorts_);
      if (other.destinationPort_ != null) {
        if (destinationPort_ == null || other.DestinationPort != 0) {
          DestinationPort = other.DestinationPort;
        }
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            sniDomains_.AddEntriesFrom(input, _repeated_sniDomains_codec);
            break;
          }
          case 26: {
            prefixRanges_.AddEntriesFrom(input, _repeated_prefixRanges_codec);
            break;
          }
          case 34: {
            AddressSuffix = input.ReadString();
            break;
          }
          case 42: {
            uint? value = _single_suffixLen_codec.Read(input);
            if (suffixLen_ == null || value != 0) {
              SuffixLen = value;
            }
            break;
          }
          case 50: {
            sourcePrefixRanges_.AddEntriesFrom(input, _repeated_sourcePrefixRanges_codec);
            break;
          }
          case 58: {
            sourcePorts_.AddEntriesFrom(input, _repeated_sourcePorts_codec);
            break;
          }
          case 66: {
            uint? value = _single_destinationPort_codec.Read(input);
            if (destinationPort_ == null || value != 0) {
              DestinationPort = value;
            }
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// A filter chain wraps a set of match criteria, an option TLS context, a set of filters, and
  /// various other parameters.
  /// </summary>
  public sealed partial class FilterChain : pb::IMessage<FilterChain> {
    private static readonly pb::MessageParser<FilterChain> _parser = new pb::MessageParser<FilterChain>(() => new FilterChain());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FilterChain> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Api.V2.Listener2.ListenerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilterChain() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilterChain(FilterChain other) : this() {
      FilterChainMatch = other.filterChainMatch_ != null ? other.FilterChainMatch.Clone() : null;
      TlsContext = other.tlsContext_ != null ? other.TlsContext.Clone() : null;
      filters_ = other.filters_.Clone();
      UseProxyProto = other.UseProxyProto;
      Metadata = other.metadata_ != null ? other.Metadata.Clone() : null;
      TransportSocket = other.transportSocket_ != null ? other.TransportSocket.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FilterChain Clone() {
      return new FilterChain(this);
    }

    /// <summary>Field number for the "filter_chain_match" field.</summary>
    public const int FilterChainMatchFieldNumber = 1;
    private global::Envoy.Api.V2.Listener2.FilterChainMatch filterChainMatch_;
    /// <summary>
    /// The criteria to use when matching a connection to this filter chain.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Listener2.FilterChainMatch FilterChainMatch {
      get { return filterChainMatch_; }
      set {
        filterChainMatch_ = value;
      }
    }

    /// <summary>Field number for the "tls_context" field.</summary>
    public const int TlsContextFieldNumber = 2;
    private global::Envoy.Api.V2.Auth.DownstreamTlsContext tlsContext_;
    /// <summary>
    /// The TLS context for this filter chain.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Auth.DownstreamTlsContext TlsContext {
      get { return tlsContext_; }
      set {
        tlsContext_ = value;
      }
    }

    /// <summary>Field number for the "filters" field.</summary>
    public const int FiltersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Envoy.Api.V2.Listener2.Filter> _repeated_filters_codec
        = pb::FieldCodec.ForMessage(26, global::Envoy.Api.V2.Listener2.Filter.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Api.V2.Listener2.Filter> filters_ = new pbc::RepeatedField<global::Envoy.Api.V2.Listener2.Filter>();
    /// <summary>
    /// A list of individual network filters that make up the filter chain for
    /// connections established with the listener. Order matters as the filters are
    /// processed sequentially as connection events happen. Note: If the filter
    /// list is empty, the connection will close by default.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Api.V2.Listener2.Filter> Filters {
      get { return filters_; }
    }

    /// <summary>Field number for the "use_proxy_proto" field.</summary>
    public const int UseProxyProtoFieldNumber = 4;
    private static readonly pb::FieldCodec<bool?> _single_useProxyProto_codec = pb::FieldCodec.ForStructWrapper<bool>(34);
    private bool? useProxyProto_;
    /// <summary>
    /// Whether the listener should expect a PROXY protocol V1 header on new
    /// connections. If this option is enabled, the listener will assume that that
    /// remote address of the connection is the one specified in the header. Some
    /// load balancers including the AWS ELB support this option. If the option is
    /// absent or set to false, Envoy will use the physical peer address of the
    /// connection as the remote address.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool? UseProxyProto {
      get { return useProxyProto_; }
      set {
        useProxyProto_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 5;
    private global::Envoy.Api.V2.Core.Metadata metadata_;
    /// <summary>
    /// [#not-implemented-hide:] filter chain metadata.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Core.Metadata Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    /// <summary>Field number for the "transport_socket" field.</summary>
    public const int TransportSocketFieldNumber = 6;
    private global::Envoy.Api.V2.Core.TransportSocket transportSocket_;
    /// <summary>
    /// See :ref:`base.TransportSocket&lt;envoy_api_msg_core.TransportSocket>` description.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Core.TransportSocket TransportSocket {
      get { return transportSocket_; }
      set {
        transportSocket_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FilterChain);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FilterChain other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FilterChainMatch, other.FilterChainMatch)) return false;
      if (!object.Equals(TlsContext, other.TlsContext)) return false;
      if(!filters_.Equals(other.filters_)) return false;
      if (UseProxyProto != other.UseProxyProto) return false;
      if (!object.Equals(Metadata, other.Metadata)) return false;
      if (!object.Equals(TransportSocket, other.TransportSocket)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (filterChainMatch_ != null) hash ^= FilterChainMatch.GetHashCode();
      if (tlsContext_ != null) hash ^= TlsContext.GetHashCode();
      hash ^= filters_.GetHashCode();
      if (useProxyProto_ != null) hash ^= UseProxyProto.GetHashCode();
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      if (transportSocket_ != null) hash ^= TransportSocket.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (filterChainMatch_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FilterChainMatch);
      }
      if (tlsContext_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TlsContext);
      }
      filters_.WriteTo(output, _repeated_filters_codec);
      if (useProxyProto_ != null) {
        _single_useProxyProto_codec.WriteTagAndValue(output, UseProxyProto);
      }
      if (metadata_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Metadata);
      }
      if (transportSocket_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(TransportSocket);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (filterChainMatch_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FilterChainMatch);
      }
      if (tlsContext_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TlsContext);
      }
      size += filters_.CalculateSize(_repeated_filters_codec);
      if (useProxyProto_ != null) {
        size += _single_useProxyProto_codec.CalculateSizeWithTag(UseProxyProto);
      }
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      if (transportSocket_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TransportSocket);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FilterChain other) {
      if (other == null) {
        return;
      }
      if (other.filterChainMatch_ != null) {
        if (filterChainMatch_ == null) {
          filterChainMatch_ = new global::Envoy.Api.V2.Listener2.FilterChainMatch();
        }
        FilterChainMatch.MergeFrom(other.FilterChainMatch);
      }
      if (other.tlsContext_ != null) {
        if (tlsContext_ == null) {
          tlsContext_ = new global::Envoy.Api.V2.Auth.DownstreamTlsContext();
        }
        TlsContext.MergeFrom(other.TlsContext);
      }
      filters_.Add(other.filters_);
      if (other.useProxyProto_ != null) {
        if (useProxyProto_ == null || other.UseProxyProto != false) {
          UseProxyProto = other.UseProxyProto;
        }
      }
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          metadata_ = new global::Envoy.Api.V2.Core.Metadata();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      if (other.transportSocket_ != null) {
        if (transportSocket_ == null) {
          transportSocket_ = new global::Envoy.Api.V2.Core.TransportSocket();
        }
        TransportSocket.MergeFrom(other.TransportSocket);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (filterChainMatch_ == null) {
              filterChainMatch_ = new global::Envoy.Api.V2.Listener2.FilterChainMatch();
            }
            input.ReadMessage(filterChainMatch_);
            break;
          }
          case 18: {
            if (tlsContext_ == null) {
              tlsContext_ = new global::Envoy.Api.V2.Auth.DownstreamTlsContext();
            }
            input.ReadMessage(tlsContext_);
            break;
          }
          case 26: {
            filters_.AddEntriesFrom(input, _repeated_filters_codec);
            break;
          }
          case 34: {
            bool? value = _single_useProxyProto_codec.Read(input);
            if (useProxyProto_ == null || value != false) {
              UseProxyProto = value;
            }
            break;
          }
          case 42: {
            if (metadata_ == null) {
              metadata_ = new global::Envoy.Api.V2.Core.Metadata();
            }
            input.ReadMessage(metadata_);
            break;
          }
          case 50: {
            if (transportSocket_ == null) {
              transportSocket_ = new global::Envoy.Api.V2.Core.TransportSocket();
            }
            input.ReadMessage(transportSocket_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ListenerFilter : pb::IMessage<ListenerFilter> {
    private static readonly pb::MessageParser<ListenerFilter> _parser = new pb::MessageParser<ListenerFilter>(() => new ListenerFilter());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListenerFilter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Api.V2.Listener2.ListenerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenerFilter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenerFilter(ListenerFilter other) : this() {
      name_ = other.name_;
      Config = other.config_ != null ? other.Config.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListenerFilter Clone() {
      return new ListenerFilter(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The name of the filter to instantiate. The name must match a supported
    /// filter. The built-in filters are:
    ///
    /// [#comment:TODO(mattklein123): Auto generate the following list]
    /// * :ref:`envoy.listener.original_dst &lt;config_listener_filters_original_dst>`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Struct config_;
    /// <summary>
    /// Filter specific configuration which depends on the filter being
    /// instantiated. See the supported filters for further documentation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Struct Config {
      get { return config_; }
      set {
        config_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListenerFilter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListenerFilter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Config, other.Config)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (config_ != null) hash ^= Config.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (config_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Config);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (config_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListenerFilter other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.config_ != null) {
        if (config_ == null) {
          config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        Config.MergeFrom(other.Config);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (config_ == null) {
              config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(config_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
