// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http/transcoder/v2/transcoder.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Config.Filter.Http.Transcoder.V2 {

  /// <summary>Holder for reflection information generated from http/transcoder/v2/transcoder.proto</summary>
  public static partial class TranscoderReflection {

    #region Descriptor
    /// <summary>File descriptor for http/transcoder/v2/transcoder.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TranscoderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNodHRwL3RyYW5zY29kZXIvdjIvdHJhbnNjb2Rlci5wcm90bxImZW52b3ku",
            "Y29uZmlnLmZpbHRlci5odHRwLnRyYW5zY29kZXIudjIaF3ZhbGlkYXRlL3Zh",
            "bGlkYXRlLnByb3RvIv8CChJHcnBjSnNvblRyYW5zY29kZXISGgoQcHJvdG9f",
            "ZGVzY3JpcHRvchgBIAEoCUgAEh4KFHByb3RvX2Rlc2NyaXB0b3JfYmluGAQg",
            "ASgMSAASHAoIc2VydmljZXMYAiADKAlCCrrpwAMFkgECCAESXgoNcHJpbnRf",
            "b3B0aW9ucxgDIAEoCzJHLmVudm95LmNvbmZpZy5maWx0ZXIuaHR0cC50cmFu",
            "c2NvZGVyLnYyLkdycGNKc29uVHJhbnNjb2Rlci5QcmludE9wdGlvbnMalQEK",
            "DFByaW50T3B0aW9ucxIWCg5hZGRfd2hpdGVzcGFjZRgBIAEoCBIlCh1hbHdh",
            "eXNfcHJpbnRfcHJpbWl0aXZlX2ZpZWxkcxgCIAEoCBIiChphbHdheXNfcHJp",
            "bnRfZW51bXNfYXNfaW50cxgDIAEoCBIiChpwcmVzZXJ2ZV9wcm90b19maWVs",
            "ZF9uYW1lcxgEIAEoCEIXCg5kZXNjcmlwdG9yX3NldBIFuOnAAwFCBFoCdjJi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder), global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder.Parser, new[]{ "ProtoDescriptor", "ProtoDescriptorBin", "Services", "PrintOptions" }, new[]{ "DescriptorSet" }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder.Types.PrintOptions), global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder.Types.PrintOptions.Parser, new[]{ "AddWhitespace", "AlwaysPrintPrimitiveFields", "AlwaysPrintEnumsAsInts", "PreserveProtoFieldNames" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GrpcJsonTranscoder : pb::IMessage<GrpcJsonTranscoder> {
    private static readonly pb::MessageParser<GrpcJsonTranscoder> _parser = new pb::MessageParser<GrpcJsonTranscoder>(() => new GrpcJsonTranscoder());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcJsonTranscoder> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Config.Filter.Http.Transcoder.V2.TranscoderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcJsonTranscoder() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcJsonTranscoder(GrpcJsonTranscoder other) : this() {
      services_ = other.services_.Clone();
      PrintOptions = other.printOptions_ != null ? other.PrintOptions.Clone() : null;
      switch (other.DescriptorSetCase) {
        case DescriptorSetOneofCase.ProtoDescriptor:
          ProtoDescriptor = other.ProtoDescriptor;
          break;
        case DescriptorSetOneofCase.ProtoDescriptorBin:
          ProtoDescriptorBin = other.ProtoDescriptorBin;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcJsonTranscoder Clone() {
      return new GrpcJsonTranscoder(this);
    }

    /// <summary>Field number for the "proto_descriptor" field.</summary>
    public const int ProtoDescriptorFieldNumber = 1;
    /// <summary>
    /// Supplies the filename of
    /// :ref:`the proto descriptor set &lt;config_grpc_json_generate_proto_descriptor_set>` for the gRPC
    /// services.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProtoDescriptor {
      get { return descriptorSetCase_ == DescriptorSetOneofCase.ProtoDescriptor ? (string) descriptorSet_ : ""; }
      set {
        descriptorSet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        descriptorSetCase_ = DescriptorSetOneofCase.ProtoDescriptor;
      }
    }

    /// <summary>Field number for the "proto_descriptor_bin" field.</summary>
    public const int ProtoDescriptorBinFieldNumber = 4;
    /// <summary>
    /// Supplies the binary content of
    /// :ref:`the proto descriptor set &lt;config_grpc_json_generate_proto_descriptor_set>` for the gRPC
    /// services.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ProtoDescriptorBin {
      get { return descriptorSetCase_ == DescriptorSetOneofCase.ProtoDescriptorBin ? (pb::ByteString) descriptorSet_ : pb::ByteString.Empty; }
      set {
        descriptorSet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        descriptorSetCase_ = DescriptorSetOneofCase.ProtoDescriptorBin;
      }
    }

    /// <summary>Field number for the "services" field.</summary>
    public const int ServicesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_services_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> services_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// A list of strings that supplies the service names that the
    /// transcoder will translate. If the service name doesn't exist in ``proto_descriptor``, Envoy
    /// will fail at startup. The ``proto_descriptor`` may contain more services than the service names
    /// specified here, but they won't be translated.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Services {
      get { return services_; }
    }

    /// <summary>Field number for the "print_options" field.</summary>
    public const int PrintOptionsFieldNumber = 3;
    private global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder.Types.PrintOptions printOptions_;
    /// <summary>
    /// Control options for response JSON. These options are passed directly to
    /// `JsonPrintOptions &lt;https://developers.google.com/protocol-buffers/docs/reference/cpp/
    /// google.protobuf.util.json_util#JsonPrintOptions>`_.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder.Types.PrintOptions PrintOptions {
      get { return printOptions_; }
      set {
        printOptions_ = value;
      }
    }

    private object descriptorSet_;
    /// <summary>Enum of possible cases for the "descriptor_set" oneof.</summary>
    public enum DescriptorSetOneofCase {
      None = 0,
      ProtoDescriptor = 1,
      ProtoDescriptorBin = 4,
    }
    private DescriptorSetOneofCase descriptorSetCase_ = DescriptorSetOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DescriptorSetOneofCase DescriptorSetCase {
      get { return descriptorSetCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDescriptorSet() {
      descriptorSetCase_ = DescriptorSetOneofCase.None;
      descriptorSet_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcJsonTranscoder);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcJsonTranscoder other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProtoDescriptor != other.ProtoDescriptor) return false;
      if (ProtoDescriptorBin != other.ProtoDescriptorBin) return false;
      if(!services_.Equals(other.services_)) return false;
      if (!object.Equals(PrintOptions, other.PrintOptions)) return false;
      if (DescriptorSetCase != other.DescriptorSetCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (descriptorSetCase_ == DescriptorSetOneofCase.ProtoDescriptor) hash ^= ProtoDescriptor.GetHashCode();
      if (descriptorSetCase_ == DescriptorSetOneofCase.ProtoDescriptorBin) hash ^= ProtoDescriptorBin.GetHashCode();
      hash ^= services_.GetHashCode();
      if (printOptions_ != null) hash ^= PrintOptions.GetHashCode();
      hash ^= (int) descriptorSetCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (descriptorSetCase_ == DescriptorSetOneofCase.ProtoDescriptor) {
        output.WriteRawTag(10);
        output.WriteString(ProtoDescriptor);
      }
      services_.WriteTo(output, _repeated_services_codec);
      if (printOptions_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PrintOptions);
      }
      if (descriptorSetCase_ == DescriptorSetOneofCase.ProtoDescriptorBin) {
        output.WriteRawTag(34);
        output.WriteBytes(ProtoDescriptorBin);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (descriptorSetCase_ == DescriptorSetOneofCase.ProtoDescriptor) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProtoDescriptor);
      }
      if (descriptorSetCase_ == DescriptorSetOneofCase.ProtoDescriptorBin) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ProtoDescriptorBin);
      }
      size += services_.CalculateSize(_repeated_services_codec);
      if (printOptions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrintOptions);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcJsonTranscoder other) {
      if (other == null) {
        return;
      }
      services_.Add(other.services_);
      if (other.printOptions_ != null) {
        if (printOptions_ == null) {
          printOptions_ = new global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder.Types.PrintOptions();
        }
        PrintOptions.MergeFrom(other.PrintOptions);
      }
      switch (other.DescriptorSetCase) {
        case DescriptorSetOneofCase.ProtoDescriptor:
          ProtoDescriptor = other.ProtoDescriptor;
          break;
        case DescriptorSetOneofCase.ProtoDescriptorBin:
          ProtoDescriptorBin = other.ProtoDescriptorBin;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ProtoDescriptor = input.ReadString();
            break;
          }
          case 18: {
            services_.AddEntriesFrom(input, _repeated_services_codec);
            break;
          }
          case 26: {
            if (printOptions_ == null) {
              printOptions_ = new global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder.Types.PrintOptions();
            }
            input.ReadMessage(printOptions_);
            break;
          }
          case 34: {
            ProtoDescriptorBin = input.ReadBytes();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GrpcJsonTranscoder message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class PrintOptions : pb::IMessage<PrintOptions> {
        private static readonly pb::MessageParser<PrintOptions> _parser = new pb::MessageParser<PrintOptions>(() => new PrintOptions());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<PrintOptions> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Envoy.Config.Filter.Http.Transcoder.V2.GrpcJsonTranscoder.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PrintOptions() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PrintOptions(PrintOptions other) : this() {
          addWhitespace_ = other.addWhitespace_;
          alwaysPrintPrimitiveFields_ = other.alwaysPrintPrimitiveFields_;
          alwaysPrintEnumsAsInts_ = other.alwaysPrintEnumsAsInts_;
          preserveProtoFieldNames_ = other.preserveProtoFieldNames_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public PrintOptions Clone() {
          return new PrintOptions(this);
        }

        /// <summary>Field number for the "add_whitespace" field.</summary>
        public const int AddWhitespaceFieldNumber = 1;
        private bool addWhitespace_;
        /// <summary>
        /// Whether to add spaces, line breaks and indentation to make the JSON
        /// output easy to read. Defaults to false.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool AddWhitespace {
          get { return addWhitespace_; }
          set {
            addWhitespace_ = value;
          }
        }

        /// <summary>Field number for the "always_print_primitive_fields" field.</summary>
        public const int AlwaysPrintPrimitiveFieldsFieldNumber = 2;
        private bool alwaysPrintPrimitiveFields_;
        /// <summary>
        /// Whether to always print primitive fields. By default primitive
        /// fields with default values will be omitted in JSON output. For
        /// example, an int32 field set to 0 will be omitted. Setting this flag to
        /// true will override the default behavior and print primitive fields
        /// regardless of their values. Defaults to false.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool AlwaysPrintPrimitiveFields {
          get { return alwaysPrintPrimitiveFields_; }
          set {
            alwaysPrintPrimitiveFields_ = value;
          }
        }

        /// <summary>Field number for the "always_print_enums_as_ints" field.</summary>
        public const int AlwaysPrintEnumsAsIntsFieldNumber = 3;
        private bool alwaysPrintEnumsAsInts_;
        /// <summary>
        /// Whether to always print enums as ints. By default they are rendered
        /// as strings. Defaults to false.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool AlwaysPrintEnumsAsInts {
          get { return alwaysPrintEnumsAsInts_; }
          set {
            alwaysPrintEnumsAsInts_ = value;
          }
        }

        /// <summary>Field number for the "preserve_proto_field_names" field.</summary>
        public const int PreserveProtoFieldNamesFieldNumber = 4;
        private bool preserveProtoFieldNames_;
        /// <summary>
        /// Whether to preserve proto field names. By default protobuf will
        /// generate JSON field names using the ``json_name`` option, or lower camel case,
        /// in that order. Setting this flag will preserve the original field names. Defaults to false.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool PreserveProtoFieldNames {
          get { return preserveProtoFieldNames_; }
          set {
            preserveProtoFieldNames_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as PrintOptions);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(PrintOptions other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (AddWhitespace != other.AddWhitespace) return false;
          if (AlwaysPrintPrimitiveFields != other.AlwaysPrintPrimitiveFields) return false;
          if (AlwaysPrintEnumsAsInts != other.AlwaysPrintEnumsAsInts) return false;
          if (PreserveProtoFieldNames != other.PreserveProtoFieldNames) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (AddWhitespace != false) hash ^= AddWhitespace.GetHashCode();
          if (AlwaysPrintPrimitiveFields != false) hash ^= AlwaysPrintPrimitiveFields.GetHashCode();
          if (AlwaysPrintEnumsAsInts != false) hash ^= AlwaysPrintEnumsAsInts.GetHashCode();
          if (PreserveProtoFieldNames != false) hash ^= PreserveProtoFieldNames.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (AddWhitespace != false) {
            output.WriteRawTag(8);
            output.WriteBool(AddWhitespace);
          }
          if (AlwaysPrintPrimitiveFields != false) {
            output.WriteRawTag(16);
            output.WriteBool(AlwaysPrintPrimitiveFields);
          }
          if (AlwaysPrintEnumsAsInts != false) {
            output.WriteRawTag(24);
            output.WriteBool(AlwaysPrintEnumsAsInts);
          }
          if (PreserveProtoFieldNames != false) {
            output.WriteRawTag(32);
            output.WriteBool(PreserveProtoFieldNames);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (AddWhitespace != false) {
            size += 1 + 1;
          }
          if (AlwaysPrintPrimitiveFields != false) {
            size += 1 + 1;
          }
          if (AlwaysPrintEnumsAsInts != false) {
            size += 1 + 1;
          }
          if (PreserveProtoFieldNames != false) {
            size += 1 + 1;
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(PrintOptions other) {
          if (other == null) {
            return;
          }
          if (other.AddWhitespace != false) {
            AddWhitespace = other.AddWhitespace;
          }
          if (other.AlwaysPrintPrimitiveFields != false) {
            AlwaysPrintPrimitiveFields = other.AlwaysPrintPrimitiveFields;
          }
          if (other.AlwaysPrintEnumsAsInts != false) {
            AlwaysPrintEnumsAsInts = other.AlwaysPrintEnumsAsInts;
          }
          if (other.PreserveProtoFieldNames != false) {
            PreserveProtoFieldNames = other.PreserveProtoFieldNames;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                AddWhitespace = input.ReadBool();
                break;
              }
              case 16: {
                AlwaysPrintPrimitiveFields = input.ReadBool();
                break;
              }
              case 24: {
                AlwaysPrintEnumsAsInts = input.ReadBool();
                break;
              }
              case 32: {
                PreserveProtoFieldNames = input.ReadBool();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
