// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2/stats.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Envoy.Config.Metrics.V2 {

  /// <summary>Holder for reflection information generated from v2/stats.proto</summary>
  public static partial class StatsReflection {

    #region Descriptor
    /// <summary>File descriptor for v2/stats.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg52Mi9zdGF0cy5wcm90bxIXZW52b3kuY29uZmlnLm1ldHJpY3MudjIaH2Vu",
            "dm95L2FwaS92Mi9jb3JlL2FkZHJlc3MucHJvdG8aHGdvb2dsZS9wcm90b2J1",
            "Zi9zdHJ1Y3QucHJvdG8aHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVycy5wcm90",
            "bxoXdmFsaWRhdGUvdmFsaWRhdGUucHJvdG8iQgoJU3RhdHNTaW5rEgwKBG5h",
            "bWUYASABKAkSJwoGY29uZmlnGAIgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0",
            "cnVjdCKCAQoLU3RhdHNDb25maWcSOQoKc3RhdHNfdGFncxgBIAMoCzIlLmVu",
            "dm95LmNvbmZpZy5tZXRyaWNzLnYyLlRhZ1NwZWNpZmllchI4ChR1c2VfYWxs",
            "X2RlZmF1bHRfdGFncxgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5Cb29sVmFs",
            "dWUiVQoMVGFnU3BlY2lmaWVyEhAKCHRhZ19uYW1lGAEgASgJEg8KBXJlZ2V4",
            "GAIgASgJSAASFQoLZml4ZWRfdmFsdWUYAyABKAlIAEILCgl0YWdfdmFsdWUi",
            "cgoKU3RhdHNkU2luaxItCgdhZGRyZXNzGAEgASgLMhouZW52b3kuYXBpLnYy",
            "LmNvcmUuQWRkcmVzc0gAEhoKEHRjcF9jbHVzdGVyX25hbWUYAiABKAlIAEIZ",
            "ChBzdGF0c2Rfc3BlY2lmaWVyEgW46cADASJ5Cg1Eb2dTdGF0c2RTaW5rEi0K",
            "B2FkZHJlc3MYASABKAsyGi5lbnZveS5hcGkudjIuY29yZS5BZGRyZXNzSAAS",
            "GgoQdGNwX2NsdXN0ZXJfbmFtZRgCIAEoCUgAQh0KFGRvZ19zdGF0c2Rfc3Bl",
            "Y2lmaWVyEgW46cADAUIEWgJ2MmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Envoy.Api.V2.Core.AddressReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Metrics.V2.StatsSink), global::Envoy.Config.Metrics.V2.StatsSink.Parser, new[]{ "Name", "Config" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Metrics.V2.StatsConfig), global::Envoy.Config.Metrics.V2.StatsConfig.Parser, new[]{ "StatsTags", "UseAllDefaultTags" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Metrics.V2.TagSpecifier), global::Envoy.Config.Metrics.V2.TagSpecifier.Parser, new[]{ "TagName", "Regex", "FixedValue" }, new[]{ "TagValue" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Metrics.V2.StatsdSink), global::Envoy.Config.Metrics.V2.StatsdSink.Parser, new[]{ "Address", "TcpClusterName" }, new[]{ "StatsdSpecifier" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Envoy.Config.Metrics.V2.DogStatsdSink), global::Envoy.Config.Metrics.V2.DogStatsdSink.Parser, new[]{ "Address", "TcpClusterName" }, new[]{ "DogStatsdSpecifier" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Configuration for pluggable stats sinks.
  /// </summary>
  public sealed partial class StatsSink : pb::IMessage<StatsSink> {
    private static readonly pb::MessageParser<StatsSink> _parser = new pb::MessageParser<StatsSink>(() => new StatsSink());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StatsSink> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Config.Metrics.V2.StatsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsSink() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsSink(StatsSink other) : this() {
      name_ = other.name_;
      Config = other.config_ != null ? other.Config.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsSink Clone() {
      return new StatsSink(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The name of the stats sink to instantiate. The name must match a supported
    /// stats sink. The built-in stats sinks are:
    ///
    /// * :ref:`envoy.statsd &lt;envoy_api_msg_config.metrics.v2.StatsdSink>`
    /// * :ref:`envoy.dog_statsd &lt;envoy_api_msg_config.metrics.v2.DogStatsdSink>`
    /// * :ref:`envoy.metrics_service &lt;envoy_api_msg_config.metrics.v2.MetricsServiceConfig>`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Struct config_;
    /// <summary>
    /// Stats sink specific configuration which depends on the sink being
    /// instantiated. See :ref:`StatsdSink &lt;envoy_api_msg_config.metrics.v2.StatsdSink>` for an
    /// example.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Struct Config {
      get { return config_; }
      set {
        config_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StatsSink);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StatsSink other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Config, other.Config)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (config_ != null) hash ^= Config.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (config_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Config);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (config_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StatsSink other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.config_ != null) {
        if (config_ == null) {
          config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        Config.MergeFrom(other.Config);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (config_ == null) {
              config_ = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(config_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Statistics configuration such as tagging.
  /// </summary>
  public sealed partial class StatsConfig : pb::IMessage<StatsConfig> {
    private static readonly pb::MessageParser<StatsConfig> _parser = new pb::MessageParser<StatsConfig>(() => new StatsConfig());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StatsConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Config.Metrics.V2.StatsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsConfig(StatsConfig other) : this() {
      statsTags_ = other.statsTags_.Clone();
      UseAllDefaultTags = other.UseAllDefaultTags;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsConfig Clone() {
      return new StatsConfig(this);
    }

    /// <summary>Field number for the "stats_tags" field.</summary>
    public const int StatsTagsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Envoy.Config.Metrics.V2.TagSpecifier> _repeated_statsTags_codec
        = pb::FieldCodec.ForMessage(10, global::Envoy.Config.Metrics.V2.TagSpecifier.Parser);
    private readonly pbc::RepeatedField<global::Envoy.Config.Metrics.V2.TagSpecifier> statsTags_ = new pbc::RepeatedField<global::Envoy.Config.Metrics.V2.TagSpecifier>();
    /// <summary>
    /// Each stat name is iteratively processed through these tag specifiers.
    /// When a tag is matched, the first capture group is removed from the name so
    /// later :ref:`TagSpecifiers &lt;envoy_api_msg_config.metrics.v2.TagSpecifier>` cannot match that
    /// same portion of the match.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Envoy.Config.Metrics.V2.TagSpecifier> StatsTags {
      get { return statsTags_; }
    }

    /// <summary>Field number for the "use_all_default_tags" field.</summary>
    public const int UseAllDefaultTagsFieldNumber = 2;
    private static readonly pb::FieldCodec<bool?> _single_useAllDefaultTags_codec = pb::FieldCodec.ForStructWrapper<bool>(18);
    private bool? useAllDefaultTags_;
    /// <summary>
    /// Use all default tag regexes specified in Envoy. These can be combined with
    /// custom tags specified in :ref:`stats_tags
    /// &lt;envoy_api_field_config.metrics.v2.StatsConfig.stats_tags>`. They will be processed before
    /// the custom tags.
    ///
    /// .. note::
    ///
    ///   If any default tags are specified twice, the config will be considered
    ///   invalid.
    ///
    /// See `well_known_names.h
    /// &lt;https://github.com/envoyproxy/envoy/blob/master/source/common/config/well_known_names.h>`_
    /// for a list of the default tags in Envoy.
    ///
    /// If not provided, the value is assumed to be true.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool? UseAllDefaultTags {
      get { return useAllDefaultTags_; }
      set {
        useAllDefaultTags_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StatsConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StatsConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!statsTags_.Equals(other.statsTags_)) return false;
      if (UseAllDefaultTags != other.UseAllDefaultTags) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= statsTags_.GetHashCode();
      if (useAllDefaultTags_ != null) hash ^= UseAllDefaultTags.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      statsTags_.WriteTo(output, _repeated_statsTags_codec);
      if (useAllDefaultTags_ != null) {
        _single_useAllDefaultTags_codec.WriteTagAndValue(output, UseAllDefaultTags);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += statsTags_.CalculateSize(_repeated_statsTags_codec);
      if (useAllDefaultTags_ != null) {
        size += _single_useAllDefaultTags_codec.CalculateSizeWithTag(UseAllDefaultTags);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StatsConfig other) {
      if (other == null) {
        return;
      }
      statsTags_.Add(other.statsTags_);
      if (other.useAllDefaultTags_ != null) {
        if (useAllDefaultTags_ == null || other.UseAllDefaultTags != false) {
          UseAllDefaultTags = other.UseAllDefaultTags;
        }
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            statsTags_.AddEntriesFrom(input, _repeated_statsTags_codec);
            break;
          }
          case 18: {
            bool? value = _single_useAllDefaultTags_codec.Read(input);
            if (useAllDefaultTags_ == null || value != false) {
              UseAllDefaultTags = value;
            }
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Designates a tag name and value pair. The value may be either a fixed value
  /// or a regex providing the value via capture groups. The specified tag will be
  /// unconditionally set if a fixed value, otherwise it will only be set if one
  /// or more capture groups in the regex match.
  /// </summary>
  public sealed partial class TagSpecifier : pb::IMessage<TagSpecifier> {
    private static readonly pb::MessageParser<TagSpecifier> _parser = new pb::MessageParser<TagSpecifier>(() => new TagSpecifier());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TagSpecifier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Config.Metrics.V2.StatsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TagSpecifier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TagSpecifier(TagSpecifier other) : this() {
      tagName_ = other.tagName_;
      switch (other.TagValueCase) {
        case TagValueOneofCase.Regex:
          Regex = other.Regex;
          break;
        case TagValueOneofCase.FixedValue:
          FixedValue = other.FixedValue;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TagSpecifier Clone() {
      return new TagSpecifier(this);
    }

    /// <summary>Field number for the "tag_name" field.</summary>
    public const int TagNameFieldNumber = 1;
    private string tagName_ = "";
    /// <summary>
    /// Attaches an identifier to the tag values to identify the tag being in the
    /// sink. Envoy has a set of default names and regexes to extract dynamic
    /// portions of existing stats, which can be found in `well_known_names.h
    /// &lt;https://github.com/envoyproxy/envoy/blob/master/source/common/config/well_known_names.h>`_
    /// in the Envoy repository. If a :ref:`tag_name
    /// &lt;envoy_api_field_config.metrics.v2.TagSpecifier.tag_name>` is provided in the config and
    /// neither :ref:`regex &lt;envoy_api_field_config.metrics.v2.TagSpecifier.regex>` or
    /// :ref:`fixed_value &lt;envoy_api_field_config.metrics.v2.TagSpecifier.fixed_value>` were specified,
    /// Envoy will attempt to find that name in its set of defaults and use the accompanying regex.
    ///
    /// .. note::
    ///
    ///   It is invalid to specify the same tag name twice in a config.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TagName {
      get { return tagName_; }
      set {
        tagName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "regex" field.</summary>
    public const int RegexFieldNumber = 2;
    /// <summary>
    /// Designates a tag to strip from the tag extracted name and provide as a named
    /// tag value for all statistics. This will only occur if any part of the name
    /// matches the regex provided with one or more capture groups.
    ///
    /// The first capture group identifies the portion of the name to remove. The
    /// second capture group (which will normally be nested inside the first) will
    /// designate the value of the tag for the statistic. If no second capture
    /// group is provided, the first will also be used to set the value of the tag.
    /// All other capture groups will be ignored.
    ///
    /// Example 1. a stat name ``cluster.foo_cluster.upstream_rq_timeout`` and
    /// one tag specifier:
    ///
    /// .. code-block:: json
    ///
    ///   {
    ///     "tag_name": "envoy.cluster_name",
    ///     "regex": "^cluster\.((.+?)\.)"
    ///   }
    ///
    /// Note that the regex will remove ``foo_cluster.`` making the tag extracted
    /// name ``cluster.upstream_rq_timeout`` and the tag value for
    /// ``envoy.cluster_name`` will be ``foo_cluster`` (note: there will be no
    /// ``.`` character because of the second capture group).
    ///
    /// Example 2. a stat name
    /// ``http.connection_manager_1.user_agent.ios.downstream_cx_total`` and two
    /// tag specifiers:
    ///
    /// .. code-block:: json
    ///
    ///   [
    ///     {
    ///       "tag_name": "envoy.http_user_agent",
    ///       "regex": "^http(?=\.).*?\.user_agent\.((.+?)\.)\w+?$"
    ///     },
    ///     {
    ///       "tag_name": "envoy.http_conn_manager_prefix",
    ///       "regex": "^http\.((.*?)\.)"
    ///     }
    ///   ]
    ///
    /// The two regexes of the specifiers will be processed in the definition order.
    ///
    /// The first regex will remove ``ios.``, leaving the tag extracted name
    /// ``http.connection_manager_1.user_agent.downstream_cx_total``. The tag
    /// ``envoy.http_user_agent`` will be added with tag value ``ios``.
    ///
    /// The second regex will remove ``connection_manager_1.`` from the tag
    /// extracted name produced by the first regex
    /// ``http.connection_manager_1.user_agent.downstream_cx_total``, leaving
    /// ``http.user_agent.downstream_cx_total`` as the tag extracted name. The tag
    /// ``envoy.http_conn_manager_prefix`` will be added with the tag value
    /// ``connection_manager_1``.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Regex {
      get { return tagValueCase_ == TagValueOneofCase.Regex ? (string) tagValue_ : ""; }
      set {
        tagValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        tagValueCase_ = TagValueOneofCase.Regex;
      }
    }

    /// <summary>Field number for the "fixed_value" field.</summary>
    public const int FixedValueFieldNumber = 3;
    /// <summary>
    /// Specifies a fixed tag value for the ``tag_name``.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FixedValue {
      get { return tagValueCase_ == TagValueOneofCase.FixedValue ? (string) tagValue_ : ""; }
      set {
        tagValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        tagValueCase_ = TagValueOneofCase.FixedValue;
      }
    }

    private object tagValue_;
    /// <summary>Enum of possible cases for the "tag_value" oneof.</summary>
    public enum TagValueOneofCase {
      None = 0,
      Regex = 2,
      FixedValue = 3,
    }
    private TagValueOneofCase tagValueCase_ = TagValueOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TagValueOneofCase TagValueCase {
      get { return tagValueCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTagValue() {
      tagValueCase_ = TagValueOneofCase.None;
      tagValue_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TagSpecifier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TagSpecifier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TagName != other.TagName) return false;
      if (Regex != other.Regex) return false;
      if (FixedValue != other.FixedValue) return false;
      if (TagValueCase != other.TagValueCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TagName.Length != 0) hash ^= TagName.GetHashCode();
      if (tagValueCase_ == TagValueOneofCase.Regex) hash ^= Regex.GetHashCode();
      if (tagValueCase_ == TagValueOneofCase.FixedValue) hash ^= FixedValue.GetHashCode();
      hash ^= (int) tagValueCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TagName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TagName);
      }
      if (tagValueCase_ == TagValueOneofCase.Regex) {
        output.WriteRawTag(18);
        output.WriteString(Regex);
      }
      if (tagValueCase_ == TagValueOneofCase.FixedValue) {
        output.WriteRawTag(26);
        output.WriteString(FixedValue);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TagName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TagName);
      }
      if (tagValueCase_ == TagValueOneofCase.Regex) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Regex);
      }
      if (tagValueCase_ == TagValueOneofCase.FixedValue) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FixedValue);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TagSpecifier other) {
      if (other == null) {
        return;
      }
      if (other.TagName.Length != 0) {
        TagName = other.TagName;
      }
      switch (other.TagValueCase) {
        case TagValueOneofCase.Regex:
          Regex = other.Regex;
          break;
        case TagValueOneofCase.FixedValue:
          FixedValue = other.FixedValue;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            TagName = input.ReadString();
            break;
          }
          case 18: {
            Regex = input.ReadString();
            break;
          }
          case 26: {
            FixedValue = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Stats configuration proto schema for built-in *envoy.statsd* sink.
  /// </summary>
  public sealed partial class StatsdSink : pb::IMessage<StatsdSink> {
    private static readonly pb::MessageParser<StatsdSink> _parser = new pb::MessageParser<StatsdSink>(() => new StatsdSink());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StatsdSink> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Config.Metrics.V2.StatsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsdSink() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsdSink(StatsdSink other) : this() {
      switch (other.StatsdSpecifierCase) {
        case StatsdSpecifierOneofCase.Address:
          Address = other.Address.Clone();
          break;
        case StatsdSpecifierOneofCase.TcpClusterName:
          TcpClusterName = other.TcpClusterName;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsdSink Clone() {
      return new StatsdSink(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    /// <summary>
    /// The UDP address of a running `statsd &lt;https://github.com/etsy/statsd>`_
    /// compliant listener. If specified, statistics will be flushed to this
    /// address.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Core.Address Address {
      get { return statsdSpecifierCase_ == StatsdSpecifierOneofCase.Address ? (global::Envoy.Api.V2.Core.Address) statsdSpecifier_ : null; }
      set {
        statsdSpecifier_ = value;
        statsdSpecifierCase_ = value == null ? StatsdSpecifierOneofCase.None : StatsdSpecifierOneofCase.Address;
      }
    }

    /// <summary>Field number for the "tcp_cluster_name" field.</summary>
    public const int TcpClusterNameFieldNumber = 2;
    /// <summary>
    /// The name of a cluster that is running a TCP `statsd
    /// &lt;https://github.com/etsy/statsd>`_ compliant listener. If specified,
    /// Envoy will connect to this cluster to flush statistics.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TcpClusterName {
      get { return statsdSpecifierCase_ == StatsdSpecifierOneofCase.TcpClusterName ? (string) statsdSpecifier_ : ""; }
      set {
        statsdSpecifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        statsdSpecifierCase_ = StatsdSpecifierOneofCase.TcpClusterName;
      }
    }

    private object statsdSpecifier_;
    /// <summary>Enum of possible cases for the "statsd_specifier" oneof.</summary>
    public enum StatsdSpecifierOneofCase {
      None = 0,
      Address = 1,
      TcpClusterName = 2,
    }
    private StatsdSpecifierOneofCase statsdSpecifierCase_ = StatsdSpecifierOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StatsdSpecifierOneofCase StatsdSpecifierCase {
      get { return statsdSpecifierCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearStatsdSpecifier() {
      statsdSpecifierCase_ = StatsdSpecifierOneofCase.None;
      statsdSpecifier_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StatsdSink);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StatsdSink other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Address, other.Address)) return false;
      if (TcpClusterName != other.TcpClusterName) return false;
      if (StatsdSpecifierCase != other.StatsdSpecifierCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (statsdSpecifierCase_ == StatsdSpecifierOneofCase.Address) hash ^= Address.GetHashCode();
      if (statsdSpecifierCase_ == StatsdSpecifierOneofCase.TcpClusterName) hash ^= TcpClusterName.GetHashCode();
      hash ^= (int) statsdSpecifierCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (statsdSpecifierCase_ == StatsdSpecifierOneofCase.Address) {
        output.WriteRawTag(10);
        output.WriteMessage(Address);
      }
      if (statsdSpecifierCase_ == StatsdSpecifierOneofCase.TcpClusterName) {
        output.WriteRawTag(18);
        output.WriteString(TcpClusterName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (statsdSpecifierCase_ == StatsdSpecifierOneofCase.Address) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (statsdSpecifierCase_ == StatsdSpecifierOneofCase.TcpClusterName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TcpClusterName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StatsdSink other) {
      if (other == null) {
        return;
      }
      switch (other.StatsdSpecifierCase) {
        case StatsdSpecifierOneofCase.Address:
          if (Address == null) {
            Address = new global::Envoy.Api.V2.Core.Address();
          }
          Address.MergeFrom(other.Address);
          break;
        case StatsdSpecifierOneofCase.TcpClusterName:
          TcpClusterName = other.TcpClusterName;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            global::Envoy.Api.V2.Core.Address subBuilder = new global::Envoy.Api.V2.Core.Address();
            if (statsdSpecifierCase_ == StatsdSpecifierOneofCase.Address) {
              subBuilder.MergeFrom(Address);
            }
            input.ReadMessage(subBuilder);
            Address = subBuilder;
            break;
          }
          case 18: {
            TcpClusterName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Stats configuration proto schema for built-in *envoy.dog_statsd* sink.
  /// The sink emits stats with `DogStatsD &lt;https://docs.datadoghq.com/guides/dogstatsd/>`_
  /// compatible tags. Tags are configurable via :ref:`StatsConfig
  /// &lt;envoy_api_msg_config.metrics.v2.StatsConfig>`.
  /// </summary>
  public sealed partial class DogStatsdSink : pb::IMessage<DogStatsdSink> {
    private static readonly pb::MessageParser<DogStatsdSink> _parser = new pb::MessageParser<DogStatsdSink>(() => new DogStatsdSink());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DogStatsdSink> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Envoy.Config.Metrics.V2.StatsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DogStatsdSink() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DogStatsdSink(DogStatsdSink other) : this() {
      switch (other.DogStatsdSpecifierCase) {
        case DogStatsdSpecifierOneofCase.Address:
          Address = other.Address.Clone();
          break;
        case DogStatsdSpecifierOneofCase.TcpClusterName:
          TcpClusterName = other.TcpClusterName;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DogStatsdSink Clone() {
      return new DogStatsdSink(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    /// <summary>
    /// The UDP address of a running DogStatsD compliant listener. If specified,
    /// statistics will be flushed to this address.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Envoy.Api.V2.Core.Address Address {
      get { return dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.Address ? (global::Envoy.Api.V2.Core.Address) dogStatsdSpecifier_ : null; }
      set {
        dogStatsdSpecifier_ = value;
        dogStatsdSpecifierCase_ = value == null ? DogStatsdSpecifierOneofCase.None : DogStatsdSpecifierOneofCase.Address;
      }
    }

    /// <summary>Field number for the "tcp_cluster_name" field.</summary>
    public const int TcpClusterNameFieldNumber = 2;
    /// <summary>
    /// The name of a cluster that is DogStatsD compliant TCP listener. If specified,
    /// Envoy will connect to this cluster to flush statistics.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TcpClusterName {
      get { return dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.TcpClusterName ? (string) dogStatsdSpecifier_ : ""; }
      set {
        dogStatsdSpecifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dogStatsdSpecifierCase_ = DogStatsdSpecifierOneofCase.TcpClusterName;
      }
    }

    private object dogStatsdSpecifier_;
    /// <summary>Enum of possible cases for the "dog_statsd_specifier" oneof.</summary>
    public enum DogStatsdSpecifierOneofCase {
      None = 0,
      Address = 1,
      TcpClusterName = 2,
    }
    private DogStatsdSpecifierOneofCase dogStatsdSpecifierCase_ = DogStatsdSpecifierOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DogStatsdSpecifierOneofCase DogStatsdSpecifierCase {
      get { return dogStatsdSpecifierCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDogStatsdSpecifier() {
      dogStatsdSpecifierCase_ = DogStatsdSpecifierOneofCase.None;
      dogStatsdSpecifier_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DogStatsdSink);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DogStatsdSink other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Address, other.Address)) return false;
      if (TcpClusterName != other.TcpClusterName) return false;
      if (DogStatsdSpecifierCase != other.DogStatsdSpecifierCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.Address) hash ^= Address.GetHashCode();
      if (dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.TcpClusterName) hash ^= TcpClusterName.GetHashCode();
      hash ^= (int) dogStatsdSpecifierCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.Address) {
        output.WriteRawTag(10);
        output.WriteMessage(Address);
      }
      if (dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.TcpClusterName) {
        output.WriteRawTag(18);
        output.WriteString(TcpClusterName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.Address) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      if (dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.TcpClusterName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TcpClusterName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DogStatsdSink other) {
      if (other == null) {
        return;
      }
      switch (other.DogStatsdSpecifierCase) {
        case DogStatsdSpecifierOneofCase.Address:
          if (Address == null) {
            Address = new global::Envoy.Api.V2.Core.Address();
          }
          Address.MergeFrom(other.Address);
          break;
        case DogStatsdSpecifierOneofCase.TcpClusterName:
          TcpClusterName = other.TcpClusterName;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            global::Envoy.Api.V2.Core.Address subBuilder = new global::Envoy.Api.V2.Core.Address();
            if (dogStatsdSpecifierCase_ == DogStatsdSpecifierOneofCase.Address) {
              subBuilder.MergeFrom(Address);
            }
            input.ReadMessage(subBuilder);
            Address = subBuilder;
            break;
          }
          case 18: {
            TcpClusterName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
